spring.application.name=music-player
spring.data.mongodb.uri=mongodb+srv://moorege2:25foot23@cluster0.xuq2e43.mongodb.net/songsDB
mongodb+srv://burnhaar_db_user:Baileymaggie_23@cluster0.hhvr1sk.mongodb.net/?appName=Cluster0
server.port=8080