spring.application.name=music-player
spring.mongodb.uri=mongodb+srv://moorege2:25foot23@cluster0.xuq2e43.mongodb.net/musicdb?retryWrites=true&w=majority&appName=Cluster0
server.port=8080
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**